package urlvalidator

var serviceDomainMap = map[string][]string{
	"bilibili":    {"bilibili.com", "b23.tv"},
	"bluesky":     {"bsky.app"},
	"dailymotion": {"dailymotion.com", "dai.ly"},
	"facebook":    {"facebook.com", "fb.watch", "m.facebook.com"},
	"instagram":   {"instagram.com", "www.instagram.com"},
	"loom":        {"loom.com"},
	"newgrounds":  {"newgrounds.com"},
	"ok":          {"ok.ru"},
	"pinterest":   {"pinterest.com", "pin.it"},
	"reddit":      {"reddit.com", "redd.it"},
	"rutube":      {"rutube.ru"},
	"snapchat":    {"snapchat.com"},
	"soundcloud":  {"soundcloud.com"},
	"streamable":  {"streamable.com"},
	"tiktok":      {"tiktok.com", "vm.tiktok.com", "vt.tiktok.com"},
	"tumblr":      {"tumblr.com"},
	"twitch":      {"twitch.tv", "clips.twitch.tv"},
	"twitter":     {"twitter.com", "x.com", "fxtwitter.com", "vxtwitter.com"},
	"vimeo":       {"vimeo.com", "player.vimeo.com"},
	"vk":          {"vk.com", "m.vk.com"},
	"xiaohongshu": {"xiaohongshu.com", "xhslink.com"},
	"youtube":     {"youtube.com", "youtu.be", "m.youtube.com", "music.youtube.com"},
}
